### ISSUE TITLE
PaxosKV在跨机房环境下响应耗时

### ISSUE THREAD

**Issue by xianglinghui** [Tencent/paxosstore#14]
Hi，挺感谢你们能够开源paxosstore，想问下，"微信PaxosStore内存篇：十亿Paxos/分钟的挑战" 这篇文章结尾处提供了PaxosKV的压测性能，平均耗时是7.28ms，这是在6台机器都部署在同机房的环境下测的吗？在跨机房部署的环境下，相应耗时会怎么样？

**Comment by dengoswei** [comment]
hi, xianglinghui. 
文章中提及的压测是标准的kv6架构下的1组: 6台机器, 分布在3个园区, 路由策略保证每个key的A/B/C三个角色分别在三个园区, 所以这里是同个IDC不同机房的压测数据. 
压测环境是我们内部上海IDC, 机房之间的ping大概在1~2ms左右.

**Comment by xianglinghui** [comment]
你们有没有遇到过，当某园区机房网络出现波动，从而读写耗时大幅提升的情况呢?

**Comment by dengoswei** [comment]
某园区机房网络抖动情况下, 一般前端侧统计的平均耗时会升到比较高, 主要是因为对网络问题园区connect的统计耗时; 实际请求耗时应该只有略为升高的.
