### ISSUE TITLE
无法执行certain中的card-srv及其他工具

### ISSUE THREAD

**Issue by lwjyqjykn** [Tencent/paxosstore#18]
我已经按照步骤成功编译出了可执行文件，且没有任何错误，但是执行时，却没有任何反应，即使在里面写一句helloworld亦无法打印，请问是编译出了什么问题还是缺少其他库引起该问题，有人遇到过同样的问题吗

**Comment by codeeply** [comment]
@lwjyqjykn 没什么反应，是指没任何东西打印到屏幕吗？你可以先看看进程是不是还活着，或者看看日志输出。
