### ISSUE TITLE
Certain组件的性能问题

### ISSUE THREAD

**Issue by lwjyqjykn** [Tencent/paxosstore#19]
请问目前PaxosStore的组件开源完了吗，经测试，Certain的入库性能很差，能否提供官方的性能指标

**Comment by codeeply** [comment]
hi @lwjyqjykn 这可能跟你的测试环境，测试方法有关，还有参数的调节。

给出的例子是基于原生gRPC和rocksdb的，
为了可以在低配的机器上直接运行，一些参数的默认值都调小了。
例子开200个plog在内部测试环境（24核CPU/32G内存/SSD）的结果大概是6~7w/s，
这个结果还有优化空间。

内部完整的PaxosStore系统，包括了支持协程的RPC框架/存储引擎，会有一些额外的优化。
