### ISSUE TITLE
rdtscp这个指令有问题 

### ISSUE THREAD

**Issue by crestxu** [Tencent/paxosstore#4]
https://github.com/Tencent/paxosstore/blob/d83137bd667e84b568ae96e06ea0b52f4c8372d2/certain/utils/FooHook.h#L12

应该替换成 
    struct timeval now = { 0 };
    gettimeofday( &now,NULL );
    unsigned long long u = now.tv_sec;
    u *= 1000;
    u += now.tv_usec / 1000;
    return u;

**Comment by dengoswei** [comment]
crest总好. 问题是 ? 内部旧代码一直在不严格的场景用RDTSCP, 精确的用gettimeofday..

**Comment by crestxu** [comment]
我的机器上没有这个指令，哈哈哈

**Comment by dengoswei** [comment]
参照libco, 默认不用RDTSCP.. 最新代码.
